name: seldo
channels:
  - defaults
dependencies:
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.8.12
  - readline=8.1
  - setuptools=58.0.4
  - sqlite=3.36.0
  - tk=8.6.11
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - attrs==21.4.0
    - crlibm==1.0.3
    - cycler==0.11.0
    - fonttools==4.28.3
    - iniconfig==1.1.1
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - matplotlib==3.5.1
    - numpy==1.21.4
    - packaging==21.3
    - pandas==1.4.1
    - pillow==8.4.0
    - pluggy==1.0.0
    - py==1.11.0
    - pyinterval==1.2.0
    - pyparsing==3.0.6
    - pytest==7.0.1
    - python-dateutil==2.8.2
    - graphviz==0.19.1
    - pytz==2021.3
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - six==1.16.0
    - threadpoolctl==3.0.0
    - tomli==2.0.1
prefix: /Users/ahoag/anaconda3/envs/seldo
